### PR TITLE
Added Educational Attainment - Autumn 2017 folder

### PR DESCRIPTION
**Pull request by oislen**
The Educational Attainment - Autumn 2017 folder contains two files; an R script for the educational attainment analysis and the 2016 CSO data census data used within the R script

### CODE REVIEW

**Review by cormac85 — COMMENTED** [review]
Good commenting, glad to see it.

My one concern is that there are comments with reference to a certain number of people in a certain prison in a certain age group. 

@colmcoughlan @oislen Is this ok? should these be removed?

**Comment by oislen** [comment]
Hey Cormac, really sorry for taking so long to reply. Yea very good point, I agree the comments should probably be removed. Those detailed comments are not essential to the script and they are detrimental to the privacy of the information collected within the IPRT surveys. Will I remove them and register another pull request? @colmcoughlan @cormac85

**Comment by cormac85** [comment]
Hang on and I'll make a suggested edit to this request.

**Comment by cormac85** [comment]
Please remove the comments that have data in them.

**Review by cormac85 — CHANGES_REQUESTED** [review]
Please remove comments with data in them from IPRT_education_analysis.R

**Comment by cormac85** [comment]
@oislen I just added a change requested review, apparently you can push your changes and we can accept them now.

**Comment by oislen** [comment]
Hey Cormac, yea I have reviewed the R script and deleted the comments with data in them. @cormac85

**Pull request merged**
